import SocialMedia from '@/components/SocialMedias/page'
import { Roboto_Slab as RobotoSlab } from 'next/font/google'

import '@/styles/globals.css'
import '@/styles/reusedStyles.css'
import '@/styles/typingEfect.css'
import { ReactNode } from 'react'

const robotoSlab = RobotoSlab({ subsets: ['latin'] })

export const metadata = {
  title: 'DevClaudioFilho | Portifolio Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        <SocialMedia />
        {children}
      </body>
    </html>
  )
}
